NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

ACCOUNTS=[
  "GABER3CCXQ44LCM5CBHKCPRNLMJFEKN2QKBQHQPJD6TFV3WXU63PKXRP"
]

[DOCUMENTATION]
ORG_NAME="LEXORA"
ORG_DBA="VANTA"
ORG_DESCRIPTION="VANTA asset information for the Lexora ecosystem."

[[CURRENCIES]]
code="VANTA"
issuer="GABER3CCXQ44LCM5CBHKCPRNLMJFEKN2QKBQHQPJD6TFV3WXU63PKXRP"
name="VANTA"
desc="VANTA is a Stellar asset in the Lexora ecosystem."
status="live"
display_decimals=7
is_asset_anchored=false
